device:
  pulse_pin: 17
  debounce: "110ms"
  denoise: "29ms"
  timeout: "110ms"

# Some devices have "enable" pins to start/stop money input.
enable_pin_control: true
# Specify if enable_pin_control is enabled.
enable_pin: 27
# Is it enabled when the signal is high?
enabled_when_high: false

# pulses: amount
values:
  2: 10
  4: 20
  10: 50
  20: 100
  40: 200

mqtt:
  brokers:
    - "mqtt://127.0.0.1:1883"
  topic: "pulseacceptord"
  client_id: "pulseacceptord-1"
