device:
  pin: 17
  debounce: 110ms
  denoise: 29ms

redis:
  tag: pulseacceptord-1
  network: tcp
  address: 127.0.0.1:6379
  db: 1
  queue: acceptors

# pulses: amount
values:
  2: 10
  4: 20
  10: 50
  20: 100
  40: 200
